// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfaeehjtxjhjkepuxdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYWVlaGp0eGpoamtlcHV4ZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTE4OTYsImV4cCI6MjA1NTYyNzg5Nn0.xt1a-zvCTzjlTONpn3jjmkQ5IA_N7NVIkGs_m7ZSvuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);